name: Build APK - Final Solution
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-11-jdk wget unzip
        pip install buildozer kivy cython

    - name: Setup Complete Android Environment
      run: |
        # دانلود SDK
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/
        
        # دانلود NDK
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export ANDROID_NDK_HOME=$PWD/android-ndk-r25b
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        
        # قبول licenses
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        
        # نصب پکیج‌های ضروری
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "platform-tools"

    - name: Create Symlinks for Buildozer
      run: |
        # ایجاد پوشه buildozer
        mkdir -p ~/.buildozer/android/platform
        
        # کپی SDK
        cp -r android-sdk ~/.buildozer/android/platform/android-sdk
        
        # کپی NDK
        cp -r android-ndk-r25b ~/.buildozer/android/platform/android-ndk-r25b
        
        # ایجاد symlink برای sdkmanager (رفع مشکل مسیر)
        mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
        ln -sf $PWD/android-sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        
        echo "=== Verification ==="
        ls -la ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        ls -la ~/.buildozer/android/platform/android-sdk/build-tools/33.0.0/aidl

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
        export ANDROID_NDK_HOME=~/.buildozer/android/platform/android-ndk-r25b
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/build-tools/33.0.0
        
        # ساخت APK
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: final-apk
        path: bin/*.apk
