name: Build APK - Force Manual SDK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-11-jdk wget unzip
        pip install buildozer kivy cython

    - name: Download and Setup Android SDK Manually
      run: |
        # دانلود SDK
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/
        
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        
        # قبول licenses
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        
        # نصب پکیج‌های ضروری
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "platform-tools" \
          "ndk;25.1.8937393"

    - name: COMPLETELY Replace Buildozer SDK
      run: |
        # حذف کامل پوشه buildozer
        rm -rf ~/.buildozer
        
        # ایجاد پوشه‌های جدید
        mkdir -p ~/.buildozer/android/platform
        
        # کپی کامل SDK دستی
        cp -r android-sdk ~/.buildozer/android/platform/android-sdk
        
        # بررسی وجود Aidl
        echo "=== Verifying Aidl ==="
        find ~/.buildozer -name "aidl" -type f
        ls -la ~/.buildozer/android/platform/android-sdk/build-tools/33.0.0/ | grep aidl

    - name: Build APK with Forced SDK
      run: |
        export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
        export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.1.8937393
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/build-tools/33.0.0
        
        # ساخت APK
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: final-apk
        path: bin/*.apk
