name: Build APK - Complete Solution
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip openjdk-11-jdk wget unzip \
          libgl1-mesa-dev libgles2-mesa-dev \
          zlib1g-dev libsqlite3-dev libffi-dev libssl-dev
        pip install buildozer==1.5.0 kivy==2.2.1 cython==0.29.36

    - name: Setup Hybrid Android Environment
      run: |
        # دانلود SDK قدیمی (برای sdkmanager)
        wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip -q sdk-tools-linux-4333796.zip -d android-sdk-old

        # دانلود SDK جدید (برای AIDL و build-tools)
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk-new/cmdline-tools/latest
        mv cmdline-tools/* android-sdk-new/cmdline-tools/latest/

        # دانلود NDK
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip

        # استفاده از SDK قدیمی برای sdkmanager
        export ANDROID_SDK_ROOT=$PWD/android-sdk-old
        export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin

        # قبول licenses
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license

        # نصب پکیج‌ها با SDK قدیمی
        yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "platform-tools" \
          "ndk;25.1.8937393"

    - name: Create Complete Buildozer Environment
      run: |
        mkdir -p ~/.buildozer/android/platform

        # کپی SDK جدید (که AIDL دارد)
        cp -r android-sdk-new ~/.buildozer/android/platform/android-sdk

        # کپی NDK
        cp -r android-ndk-r25b ~/.buildozer/android/platform/android-ndk-r25b

        # کپی build-tools و platform-tools از SDK قدیمی
        cp -r android-sdk-old/build-tools ~/.buildozer/android/platform/android-sdk/
        cp -r android-sdk-old/platforms ~/.buildozer/android/platform/android-sdk/
        cp -r android-sdk-old/platform-tools ~/.buildozer/android/platform/android-sdk/

        # ساخت symlink صحیح برای sdkmanager
        mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
        ln -sf $PWD/android-sdk-new/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Verify AIDL and SDKManager
      run: |
        echo "=== Verification ==="
        ls -la ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        ls -la ~/.buildozer/android/platform/android-sdk/build-tools/33.0.0/aidl
        find ~/.buildozer -name "aidl" -type f

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
        export ANDROID_NDK_HOME=~/.buildozer/android/platform/android-ndk-r25b
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$PATH

        buildozer -v android debug | tee build_log.txt

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: final-apk
        path: bin/*.apk
