name: Build APK Complete
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          wget \
          unzip \
          openjdk-11-jdk \
          python3-pip \
          python3-dev \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libssl-dev \
          libreadline-dev \
          libffi-dev \
          libsqlite3-dev \
          liblzma-dev \
          make \
          build-essential \
          cython3
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.33
        pip install buildozer
        pip install kivy[base]
        
    - name: Setup Android environment
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
    - name: Accept Android licenses automatically
      run: |
        mkdir -p ~/.android/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/licenses/android-sdk-preview-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/licenses/android-sdk-arm-dbt-license
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.android/licenses/android-googletv-license
        
    - name: Build APK with force license acceptance
      run: |
        export ANDROID_SDK_HOME=$HOME
        YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BINARY=1 buildozer -v android debug
        
    - name: Check build results
      run: |
        echo "=== Build Results ==="
        ls -la bin/ 2>/dev/null || echo "No bin directory"
        find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: python-app-apk
        path: bin/*.apk
        retention-days: 30
        
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer
        retention-days: 7
