name: Build Python APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git wget unzip openjdk-11-jdk \
          python3-pip python3-dev \
          autoconf automake libtool pkg-config \
          zlib1g-dev libncurses5-dev libgdbm-dev \
          libnss3-dev libssl-dev libreadline-dev \
          libffi-dev libsqlite3-dev liblzma-dev \
          make build-essential cython3
        
    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.33
        pip install kivy[base]
        
    - name: Build APK with forced SDK
      run: |
        # حذف SDK قدیمی Buildozer
        rm -rf ~/.buildozer/android/platform/android-sdk
        
        # ساخت APK با قبول licenses
        YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BINARY=1 buildozer -v android debug
        
    - name: Force accept licenses manually
      if: failure()
      run: |
        # قبول licenses به صورت دستی
        mkdir -p ~/.android/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/licenses/android-sdk-preview-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/licenses/android-sdk-arm-dbt-license
        
        # ساخت مجدد
        YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BINARY=1 buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: python-app-apk
        path: bin/*.apk
        retention-days: 30
